//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelMvcProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOda()
        {
            this.TblRezarvasyon = new HashSet<TblRezarvasyon>();
        }
    
        public int OdaID { get; set; }
        public Nullable<int> OdaNo { get; set; }
        public Nullable<int> Kat { get; set; }
        public Nullable<int> Kapasite { get; set; }
        public string Açıklama { get; set; }
        public string Telefon { get; set; }
        public string Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRezarvasyon> TblRezarvasyon { get; set; }
    }
}
